// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw4pGsrVgOrrvjCFrVOArcv2XnFx9Gn2M',
    appId: '1:328544621563:web:70090f9f75e6f2e095315e',
    messagingSenderId: '328544621563',
    projectId: 'absengeura',
    authDomain: 'absengeura.firebaseapp.com',
    storageBucket: 'absengeura.firebasestorage.app',
    measurementId: 'G-LQ7W5WSDDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfuwqi9FHy9Ja1OoeGKSmXY40x9Pa8dm0',
    appId: '1:328544621563:android:41260a5a0fd5a6d795315e',
    messagingSenderId: '328544621563',
    projectId: 'absengeura',
    storageBucket: 'absengeura.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCclSdMve5PDs_f6Y-RobYsCvmdavvveBk',
    appId: '1:328544621563:ios:f4b9f0424f7c0fb795315e',
    messagingSenderId: '328544621563',
    projectId: 'absengeura',
    storageBucket: 'absengeura.firebasestorage.app',
    iosBundleId: 'com.example.absenGeura',
  );
}
